version: "3"

services:

  charge:
    restart: always
    environment:
      - API_TOKEN=${LIGHTNING_CHARGE_API_TOKEN}
    image: charge:latest
    expose:
      - "9112"
    ports:
      - "9112:9112"
    volumes:
      - ${DATADIR}/charge:/data
      - ${DATADIR}/lightning:/etc/lightning/
      
  db:
    image: postgres
    volumes:
      - ${DATADIR}/pg:/var/lib/postgresql/data
      
  web:
    build: .
    environment:
      - FROM_EMAIL=${FROM_EMAIL}
      - BUGS_TO=${BUGS_TO}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - HOSTNAME=${HOSTNAME}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DEVISE_SECRET_KEY=${DEVISE_SECRET_KEY}
      - DATABASE_URL=postgres://postgres@db:5432
      - LIGHTNING_CHARGE_API_TOKEN=${LIGHTNING_CHARGE_API_TOKEN}
    ports:
      - "80:3000"
    depends_on:
      - db
