version: "3"

services:
      
  web:
    build: .
    environment:
      - FROM_EMAIL=${FROM_EMAIL}
      - BUGS_TO=${BUGS_TO}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - HOSTNAME=${HOSTNAME}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DEVISE_SECRET_KEY=${DEVISE_SECRET_KEY}
      - DATABASE_URL=postgres://matreon@localhost:5432
      - LIGHTNING_CHARGE_API_TOKEN=${LIGHTNING_CHARGE_API_TOKEN}
    ports:
      - "80:3000"
